# -*- coding: utf-8 -*-
"""Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPP5zc3dku8bpyzVaNkcU4Lg21rtGSyF

Esse codigo foi baseado no Curso introdutorio de LLM do HuggingFace
"""

!pip install datasets evaluate transformers[sentencepiece]

"""Funcao pipeline() que serão demonstradas:

1. feature-extraction (pega a representação vetorial do texto).
2. fill-mask (preenchimento de máscara).
3. ner (reconhecimento de entidades nomeadas).
4. question-answering (responder perguntas).
5. sentiment-analysis (análise de sentimentos).
6. summarization (sumarização).
7. text-generation (geração de texto).
8. translation (tradução).
9. zero-shot-classification (classificação “zero-shot”).

A maior parte dos modelos LLM são baseados no idioma inglê, porem tem opções de outros idiomas ou multilingual.

Para verificar funcoes e idiomas no HuggingFace, basta acessar a URL: https://huggingface.co/models
"""

from transformers import pipeline

sentimento = pipeline("sentiment-analysis")
sentimento("I love studying, especially LLM")

sentimento(
    ["I love studying, especially LLM", "I don't like studying a lot"]
)

from transformers import pipeline

classifier = pipeline("zero-shot-classification")
classifier(
    "In these examples we will learn about LLM and AI-Ge models",
    candidate_labels=["education", "business"],
)

from transformers import pipeline

generator = pipeline("text-generation")
generator(
    "you will learn the subject of"
)  # vc vai aprender a materia de...

from transformers import pipeline

generator = pipeline("text-generation", model="distilgpt2")
generator(
    "you will learn the subject of",
    max_length=30,
    num_return_sequences=2,
)

from transformers import pipeline

unmasker = pipeline("fill-mask")
unmasker("You will learn the subject of <mask> in this module.", top_k=2)

from transformers import pipeline

unmasker = pipeline("fill-mask", model="bert-base-multilingual-cased")
unmasker("Vamos aprender sobre [MASK] nesse capitulo", top_k=2)

from transformers import pipeline

ner = pipeline("ner", grouped_entities=True)
ner("My name is Samanta and I work as a Data Scientist in the city of São Paulo.")

from transformers import pipeline

question_answerer = pipeline("question-answering")
question_answerer(
    question="Where do I work?",
    context="My name is Samanta and I work as a Data Scientist in the city of São Paulo.",
)

from transformers import pipeline

summarizer = pipeline("summarization")
summarizer(
    """
    The history of São Paulo, both the state and the capital, is rich and complex, marked by different phases and influences. The founding of the city in 1554 by the Jesuit college in Pátio do Colégio is an initial milestone, followed by economic and political development that transformed it into an important regional and national center.
The Foundation and the Colonial Period:
The founding of São Paulo on January 25, 1554, by the Jesuits Manuel da Nóbrega and José de Anchieta, aimed to evangelize the indigenous populations.
The city developed as an important meeting point between Portuguese and indigenous settlers, establishing a trade in indigenous products and labor.
The gradual occupation of the territory, with the creation of other cities and production centers, boosted the economic and political growth of São Paulo.
"""
)

from transformers import pipeline

# Change `xx` to the language of the input and `yy` to the language of the desired output.
#pipe = pipeline("translation_xx_to_yy", model="facebook/nllb-200-distilled-600M")

translator = pipeline("translation_pt_to_en", model="facebook/nllb-200-distilled-600M")
translator("Curso sobre LLM")